# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e97a119d585439d7cb9654d11cf32e3394d4cd32a2d5ee68f195c9cf7bdb8f57a5d2853894017e975f0fb67862903ef4858b07804bbe997051f394c908972ea

test:
  secret_key_base: a131956a0eb45e11202a960bc579f374b3180c32a227a3c9e3baa547134439bbe5313200370e2b60cf5f6b29c590fbc114cb70212e821ec06fc589f32be93f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
